services:

  Dashy:
   image: lissy93/dashy:latest
   container_name: Dashy
   restart: always
   volumes:
     - ${BASEDATAPATH}/dashy/conf.yml:/app/public/conf.yml

  homepage:
    image: ghcr.io/gethomepage/homepage:latest
    container_name: homepage
    env_file: stack.env
    environment:
      PUID: ${UID} # optional, your user id
      PGID: ${GID} # optional, your group id
      TZ: ${TZ}
      HOMEPAGE_ALLOWED_HOSTS: ${HOMEPAGE_ALLOWED_HOSTS}
    ports:
      - 3000:3000
    volumes:
      - ${BASEDATAPATH}/homepage:/app/config # Make sure your local config directory exists
      - /var/run/docker.sock:/var/run/docker.sock:ro # optional, for docker integrations
    restart: unless-stopped
    dns:
      - ${INTERNALPIHOLE}
    networks: 
      - pihole_pihole

  firefox:
    image: lscr.io/linuxserver/firefox:latest
    container_name: firefox
    security_opt:
      - seccomp:unconfined #optional
    environment:
      - PUID=${UID} #optional
      - PGID=${GID} #optional
      - TZ=${TZ}
    volumes:
      - ${BASEDATAPATH}/firefox/config:/config
      # Defaulted folder for downloads.
      #- ${BASEDATAPATH}/firefox/Downloads:/config/Downloads
      - ${BASEDATAPATH}/firefox/Downloads:/config/Downloads
    ports:
      - 4000:3000
      - 4001:3001
    shm_size: "2gb"
    restart: unless-stopped
    networks: 
      - pihole_pihole
    dns:
      - ${INTERNALPIHOLE}
    

  code-server:
    image: lscr.io/linuxserver/code-server:4.96.4
    container_name: code-server
    environment:
      - PUID=${UID} #optional
      - PGID=${GID} #optional
      - TZ=${TZ}
      - PASSWORD=password #optional
      #- HASHED_PASSWORD= #optional
      #- SUDO_PASSWORD=password #optional
      #- SUDO_PASSWORD_HASH= #optional
      #- PROXY_DOMAIN=code-server.my.domain #optional
      - DEFAULT_WORKSPACE=/config/workspace #optional
    volumes:
      - ${BASEDATAPATH}/code-server/config:/config
      # additionals
      #- ${BASEDATAPATH}/homepage:/app/config # Make sure your local config directory exists
    ports:
      - 8443:8443
    restart: unless-stopped
    networks: 
      - pihole_pihole

  speedtest-tracker:
    image: lscr.io/linuxserver/speedtest-tracker:latest
    container_name: speedtest-tracker
    environment:
      - PUID=${UID} #optional
      - PGID=${GID} #optional
      - TZ=${TZ}
      - APP_KEY=base64:VET+v0jcvecJCVyncFVPPgBpjr5hPWLfYQdgHz4Wm98=
      - APP_URL=
      - DB_CONNECTION=sqlite
      - SPEEDTEST_SCHEDULE="6 */2 * * *"
      - APP_DEBUG=true
      #- SPEEDTEST_SERVERS=61299
      #- DB_HOST= #optional
      #- DB_PORT= #optional
      #- DB_DATABASE= #optional
      #- DB_USERNAME= #optional
      #- DB_PASSWORD= #optional
      #- DISPLAY_TIMEZONE=Etc/UTC #optional
      #- PRUNE_RESULTS_OLDER_THAN=0 #optional
    volumes:
      - ${BASEDATAPATH}/speedtest-tracker/data:/config
    ports:
      - 8008:80
    restart: unless-stopped

    

  watchtower:
    image: containrrr/watchtower
    container_name: watchtower
    environment:
      - WATCHTOWER_CLEANUP=true
      # interval in seconds
      - WATCHTOWER_POLL_INTERVAL=18000
      #- WATCHTOWER_SCHEDULE= 0 0 1 * * 1  # RUN every MONDAY at 1AM
      - TZ=${TZ}
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    # command: --interval 604800 # weekly # pihole home-assistant dashy alertmanager 
    restart: always



networks:
  pihole_pihole:
    external: true
