services:

  kasm:
    image: lscr.io/linuxserver/kasm:latest
    container_name: kasm
    privileged: true
    environment:
      - KASM_PORT=8443
  #    - DOCKER_HUB_USERNAME= #optional
      #- DOCKER_HUB_PASSWORD= #optional
      - DOCKER_MTU=1500 #optional
    volumes:
      - ${BASEDATAPATH}/kasm/data:/opt
      - ${BASEDATAPATH}/kasm/profiles:/profiles #optional
      #- /dev/input:/dev/input #optional
      #- /run/udev/data:/run/udev/data #optional
    ports:
      - 13000:3000
      - 8443:8443
    restart: unless-stopped
