version: ${COMP_VERSION}
services:
  ngingx:
    container_name: Ngingx
    image: 'jc21/nginx-proxy-manager:latest'
    restart: always
    ports:
      - '80:80'
      - '81:81'
      - '443:443'
    volumes:
      - ${BASEDATAPATH}/ngingx/data:/data
      - ${BASEDATAPATH}/ngingx/letsencrypt:/etc/letsencrypt
      - ${BASEDATAPATH}/ngingx/config/nginx.conf


networks:
  default:
    external:
      name: ngingx-network
