services:
  pihole:
    container_name: pihole
    image: pihole/pihole:latest
    restart: unless-stopped
    hostname: rpi
    # For DHCP it is recommended to remove these ports and instead add: network_mode: "host"
    ports:
      - 53:53/tcp
      - 53:53/udp
      - 8080:80
    environment:
      TZ: ${TZ}
      WEBPASSWORD: ${PASSWORD}
    dns:
      - 127.0.0.1 
    volumes:
      - '${BASEDATAPATH}/pihole/etc-pihole:/etc/pihole'
      - /etc/hosts:/etc/hosts:ro
      #- ${BASEDATAPATH}/pihole/resolv.conf:/etc/resolv.conf
      #- '${BASEDATAPATH}/pihole/etc-dnsmasq.d:/etc/dnsmasq.d'
      #- /home/user/docker/data/pihole/etc-lighttpd:/etc/lighttpd
    networks:
      pihole:
        ipv4_address: 172.19.0.6

  #orbital-sync:
#    container_name: orbital-sync
#    image: mattwebbio/orbital-sync:1
#    environment:
#      TZ: ${TZ}
#      PRIMARY_HOST_BASE_URL: 'http://192.168.0.35:8080'
#      PRIMARY_HOST_PASSWORD: ${PASSWORD}
#      SECONDARY_HOSTS_1_BASE_URL: 'http://192.168.36.102:8080'
#      SECONDARY_HOSTS_1_PASSWORD: ${PASSWORD}
#      SECONDARY_HOSTS_2_BASE_URL: 'http://192.168.0.36:8080'
#      SECONDARY_HOSTS_2_PASSWORD: ${PASSWORD}
#      INTERVAL_MINUTES: 60
#    restart: unless-stopped


  piholeExporter:
    image: ekofr/pihole-exporter:latest
    container_name: PiholeExporter
    restart: unless-stopped
    environment:
      - PIHOLE_HOSTNAME=pihole
      - PIHOLE_PORT=80
      - PIHOLE_PASSWORD=${PASSWORD}
      - PORT=9617
    ports:
      - 9617:9617
    networks:
      pihole:
        ipv4_address: 172.19.0.7

networks:
  pihole:
    ipam:
      driver: default
      config:
        - subnet: 172.19.0.0/24
