
services:
  flexget:
    image: lscr.io/linuxserver/flexget:latest
    container_name: flexget
    restart: unless-stopped
    ports :
      - 5050:5050
    volumes:
      - ${BASEDATAPATH}/flexget/data:/config
      # - ${BASEDATAPATH}/flexget/data:/data
    environment:
      - PUID={UID}
      - PGID={GID}
      - TZ=${TZ}
      - FG_WEBUI_PASSWORD=${PASSWORD}
      - FG_CONFIG_FILE=/config/.flexget/config.yml
      - FG_LOG_LEVEL=debug
      - FG_LOG_FILE=/config/flexget.log

  transmission:
    image: lscr.io/linuxserver/transmission:latest
    container_name: transmission
    environment:
      - PUID={UID}
      - PGID={GID}
 #     - PUID=0
 #     - PGID=0
      - TZ=${TZ}
      #- TRANSMISSION_WEB_HOME=/combustion-release/ #optional
      # access is covered via NGINX proxy
#      - USER=user  #optional
#      - PASS=password #optional
#      - WHITELIST=192.168.123.123 #optional
      #- PEERPORT=peerport #optional
#      - HOST_WHITELIST=dnsname list #optional
   #   - UMASK = 2
    volumes:
      - ${BASEDATAPATH}/transmission:/config
      - ${JELLYMEDIA}/Downloads:/Downloads
      - ${JELLYMEDIA}/Movies:/Movies
      - ${JELLYMEDIA}/Peliculas:/Peliculas
      - ${JELLYMEDIA}/FilmyCZ:/FilmyCZ
      - ${JELLYMEDIA}/Series:/Series
      - ${JELLYMEDIA}/SeriesES:/SeriesES
      - ${JELLYMEDIA}/SerialiCZ:/SerialiCZ
      - ${JELLYMEDIA}/SerialiCZ:/AnimeSeries
      #- /path/to/watch/folder:/watch
    ports:
     - 9091:9091
     - 51413:51413
     #- 51413:51413/udp
    restart: unless-stopped

  sonarr:
    image: lscr.io/linuxserver/sonarr:latest
    container_name: sonarr
    environment:
      - PUID={UID}
      - PGID={GID}
      - TZ=${TZ}
    volumes:
      - ${BASEDATAPATH}/sonarr:/config
      - ${JELLYMEDIA}/Downloads:/Downloads
      - ${JELLYMEDIA}/Movies:/Movies
      - ${JELLYMEDIA}/Peliculas:/Peliculas
      - ${JELLYMEDIA}/FilmyCZ:/FilmyCZ
      - ${JELLYMEDIA}/Series:/Series
      - ${JELLYMEDIA}/SeriesES:/SeriesES
      - ${JELLYMEDIA}/SerialiCZ:/SerialiCZ
      - ${JELLYMEDIA}/SerialiCZ:/AnimeSeries
    ports:
      - 8989:8989
    restart: unless-stopped

  radarr:
    image: lscr.io/linuxserver/radarr:latest
    container_name: radarr
    environment:
      - PUID={UID}
      - PGID={GID}
      - TZ=${TZ}
    volumes:
      - ${BASEDATAPATH}/radarr/data/:/config
      - ${JELLYMEDIA}/Downloads:/Downloads
      - ${JELLYMEDIA}/Movies:/Movies
      - ${JELLYMEDIA}/Peliculas:/Peliculas
      - ${JELLYMEDIA}/FilmyCZ:/FilmyCZ
      - ${JELLYMEDIA}/Series:/Series
      - ${JELLYMEDIA}/SeriesES:/SeriesES
      - ${JELLYMEDIA}/SerialiCZ:/SerialiCZ
      - ${JELLYMEDIA}/SerialiCZ:/AnimeSeries
    ports:
      - 7878:7878
    restart: unless-stopped

# Vesion para descargar en CASTELLANO solamente
  radarres:
    image: lscr.io/linuxserver/radarr:latest
    container_name: radarres
    environment:
      - PUID={UID}
      - PGID={GID}
      - TZ=${TZ}
    volumes:
      # Folder has to be changed! Careful!
      - ${BASEDATAPATH}/radarres/data/:/config
      - ${JELLYMEDIA}/Downloads:/Downloads
      - ${JELLYMEDIA}/Movies:/Movies
      - ${JELLYMEDIA}/Peliculas:/Peliculas
      - ${JELLYMEDIA}/FilmyCZ:/FilmyCZ
      - ${JELLYMEDIA}/Series:/Series
      - ${JELLYMEDIA}/SeriesES:/SeriesES
      - ${JELLYMEDIA}/SerialiCZ:/SerialiCZ
      - ${JELLYMEDIA}/SerialiCZ:/AnimeSeries
    ports:
    # change port as well
      - 7879:7878
    restart: unless-stopped

  sonarres:
    image: lscr.io/linuxserver/sonarr:latest
    container_name: sonarres
    environment:
      - PUID={UID}
      - PGID={GID}
      - TZ=${TZ}
    volumes:      
      # Folder has to be changed! Careful!
      - ${BASEDATAPATH}/sonarres:/config
      - ${JELLYMEDIA}/Downloads:/Downloads
      - ${JELLYMEDIA}/Movies:/Movies
      - ${JELLYMEDIA}/Peliculas:/Peliculas
      - ${JELLYMEDIA}/FilmyCZ:/FilmyCZ
      - ${JELLYMEDIA}/Series:/Series
      - ${JELLYMEDIA}/SeriesES:/SeriesES
      - ${JELLYMEDIA}/SerialiCZ:/SerialiCZ
      - ${JELLYMEDIA}/SerialiCZ:/AnimeSeries
    ports:
      # change port as well
      - 8990:8989
    restart: unless-stopped

# instancias para checo
  radarrcz:
    image: lscr.io/linuxserver/radarr:latest
    container_name: radarrcz
    environment:
      - PUID={UID}
      - PGID={GID}
      - TZ=${TZ}
    volumes:
      # Folder has to be changed! Careful!
      - ${BASEDATAPATH}/radarrcz/data/:/config
      - ${JELLYMEDIA}/Downloads:/Downloads
      - ${JELLYMEDIA}/Movies:/Movies
      - ${JELLYMEDIA}/Peliculas:/Peliculas
      - ${JELLYMEDIA}/FilmyCZ:/FilmyCZ
      - ${JELLYMEDIA}/Series:/Series
      - ${JELLYMEDIA}/SeriesES:/SeriesES
      - ${JELLYMEDIA}/SerialiCZ:/SerialiCZ
      - ${JELLYMEDIA}/SerialiCZ:/AnimeSeries
    ports:
    # change port as well
      - 7880:7878
    restart: unless-stopped

  sonarrcz:
    image: lscr.io/linuxserver/sonarr:latest
    container_name: sonarrcz
    environment:
      - PUID={UID}
      - PGID={GID}
      - TZ=${TZ}
    volumes:      
      # Folder has to be changed! Careful!
      - ${BASEDATAPATH}/sonarrcz:/config
      - ${JELLYMEDIA}/Downloads:/Downloads
      - ${JELLYMEDIA}/Movies:/Movies
      - ${JELLYMEDIA}/Peliculas:/Peliculas
      - ${JELLYMEDIA}/FilmyCZ:/FilmyCZ
      - ${JELLYMEDIA}/Series:/Series
      - ${JELLYMEDIA}/SeriesES:/SeriesES
      - ${JELLYMEDIA}/SerialiCZ:/SerialiCZ
      - ${JELLYMEDIA}/SerialiCZ:/AnimeSeries
    ports:
      # change port as well
      - 8991:8989
    restart: unless-stopped

  prowlarr:
    image: lscr.io/linuxserver/prowlarr:latest
    container_name: prowlarr
    environment:
      - PUID={UID}
      - PGID={GID}
      - TZ=${TZ}
    volumes:
      - ${BASEDATAPATH}/prowlarr/data:/config
    ports:
      - 9696:9696
    restart: unless-stopped

  jellyseerr:
    image: fallenbagel/jellyseerr:latest
    container_name: jellyseerr
    environment:
      - PUID={UID}
      - PGID={GID}
      - LOG_LEVEL=debug
      - TZ=${TZ}
    ports:
      - 5055:5055
    volumes:
      - ${BASEDATAPATH}/jellyseerr/config:/app/config
    restart: unless-stopped



networks:
  default:
    external:
      name: nginx_default
    # volumes:
