services:
  wg-easy:
    image: ghcr.io/wg-easy/wg-easy
    container_name: wg-easy_wireguard
    volumes:
      - ${BASEDATAPATH}/wireguard:/etc/wireguard
    environment:
      # Change this to your host's public address
      - WG_HOST=${PUBLICRPI}
      - PASSWORD_HASH=${WGHASH}
      - WG_DEFAULT_DNS=${INTERNALPIHOLE},1.1.1.1
      - PEERDNS=auto #optional
      #- WG_DEVICE="wg0"
    ports:
      # VPN port
      - 51820:51820/udp
      # web interface
      - 51821:51821/tcp
    restart: unless-stopped
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    sysctls:
      - net.ipv4.ip_forward=1
      - net.ipv4.conf.all.src_valid_mark=1
    networks: 
      - pihole_pihole

networks:
  pihole_pihole:
    external: true
